####### INSTALLING ELASTICSEARCH ON UBUNTU #######

- name: Install required modules
  apt:
    name:
      - openjdk-11-jdk
      - wget
      - apt-transport-https
      - curl
      - gnupg2
    state: present
    update_cache: yes

- name: Add the Elastic GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add the Elastic repository
  lineinfile:
    path: /etc/apt/sources.list.d/elastic-7.x.list
    line: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    create: yes

- name: Update system packages
  apt:
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Configure Elasticsearch to allow remote access
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: "network.host: 0.0.0.0"
    state: present

- name: Start and enable Elasticsearch service
  systemd:
    name: elasticsearch
    state: started
    enabled: yes

- name: Allow Elasticsearch port (9200) through UFW
  ufw:
    rule: allow
    port: "9200"
    proto: tcp

########### INSTALLING LOGSTASH ON UBUNTU #########

- name: Install Logstash
  apt:
    name: logstash
    state: present

- name: Start and enable Logstash service
  systemd:
    name: logstash
    state: started
    enabled: yes

